export const CommonMessages = {
    LOGOUT_SUCCESS: "You have logout successfully!",
    LOGOUT_FAILED: "You have not logged out successfully!",
    user_inactive: "Your Account is not Active Please contact your Account Manager!",
    PERMISSION_NOT_ALLOW: `Permission not allowed. Please connect to administrator.`,
    GET_LIST: (data: string) => `${data} list has been got successfully!`,
    GET_DATA: (data: string) => `${data} data has been got successfully!`,
    CREATED_DATA: (data: string) => `${data} has been created successfully`,
    NOT_CREATED: (data: string) => `${data} has not been created`,
    BLOCK_DATA: (data: string) => `${data} has been Blocked successfully`,
    UNBLOCK_DATA: (data: string) => `${data} has been Unblocked successfully`,
    LOGIN_SUCCESS: "You have logged in successfully",
    REGISTER_SUCCESS: "Registration successful. Please check your email to verify your account.",
    PWD_NOT_MATCH: "new password and confirm password not same!",
    USER_NOT_FOUND: "user not found",
    SUB_USER_NOT_FOUND: "Subuser not found",
    INVALID_CREDENTIALS: "Invalid credetials",
    FORGET_PASSWORD: "Reset password link sent to your email",
    INVALID_TOKEN: "Invalid or expired reset token",
    RESET_PASSWORD: "Password reset successful",
    OLD_PWD_WRONG: "Incorrect Old password!",
    SAME_PASSWORD: "New password must be unique from old password!",
    PWD_CHANGE: "Password changed successfully!",
    NO_PWD_CHANGE: "Password not changed successfully!",
    created_data: (data: string) => `${data} has been created successfully`,
    updated_data: (data: string) => `${data} has been updated successfully!`,
    deleted_data: (data: string) => `${data} has been deleted successfully!`,
    not_found: (data: string) => `${data} not found.`,
    already_exist:(data:string) => `${data} already exists`,


}